# Generated by Django 4.2.7 on 2026-02-24 06:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0003_alter_appointment_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=200)),
                ('diagnosed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['condition'],
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=200)),
                ('policy_number', models.CharField(max_length=100)),
                ('group_number', models.CharField(blank=True, max_length=100)),
                ('holder_name', models.CharField(help_text='Name of policy holder', max_length=200)),
                ('holder_relationship', models.CharField(help_text='Relationship to patient', max_length=50)),
                ('expiry_date', models.DateField()),
                ('is_primary', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryCarePhysician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('practice_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='allergy',
            options={'ordering': ['allergen'], 'verbose_name_plural': 'Allergies'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['-prescribed_date']},
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='allergy',
            name='diagnosed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allergy',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='allergy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='prescribed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medication',
            name='route',
            field=models.CharField(default='oral', help_text='e.g., oral, topical, IV', max_length=50),
        ),
        migrations.AddField(
            model_name='medication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='allergen',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='reaction',
            field=models.TextField(help_text='Description of reaction'),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='severity',
            field=models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life Threatening')], default='mild', max_length=20),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(help_text='e.g., 500mg, 10ml', max_length=100),
        ),
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Once Daily'), ('bid', 'Twice Daily'), ('tid', 'Three Times Daily'), ('qid', 'Four Times Daily'), ('q4h', 'Every 4 Hours'), ('q6h', 'Every 6 Hours'), ('q8h', 'Every 8 Hours'), ('q12h', 'Every 12 Hours'), ('prn', 'As Needed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=models.TextField(blank=True, help_text='Name, relationship, phone number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')]),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AddField(
            model_name='primarycarephysician',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primary_care_physician', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='chroniccondition',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_conditions', to='patients.patient'),
        ),
    ]
