# Generated by Django 4.2.7 on 2026-02-23 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('strength', models.CharField(help_text='e.g., 500mg, 10mg/ml', max_length=100)),
                ('form', models.CharField(help_text='e.g., tablet, capsule, liquid', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(help_text='Custom medication name if not in master list', max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Once Daily'), ('bid', 'Twice Daily'), ('tid', 'Three Times Daily'), ('qid', 'Four Times Daily'), ('q4h', 'Every 4 Hours'), ('q6h', 'Every 6 Hours'), ('q8h', 'Every 8 Hours'), ('q12h', 'Every 12 Hours'), ('prn', 'As Needed'), ('weekly', 'Once Weekly')], max_length=20)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenous'), ('im', 'Intramuscular'), ('sc', 'Subcutaneous'), ('topical', 'Topical'), ('inhalation', 'Inhalation'), ('sublingual', 'Sublingual'), ('rectal', 'Rectal')], default='oral', max_length=20)),
                ('duration', models.CharField(blank=True, help_text='e.g., 7 days, 2 weeks', max_length=100)),
                ('quantity', models.IntegerField(help_text='Total quantity to dispense')),
                ('refills', models.IntegerField(default=0)),
                ('instructions', models.TextField(help_text='Special instructions for the patient')),
                ('prescribed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('dispensed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dispensed', 'Dispensed'), ('partial', 'Partially Dispensed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('completed', 'Completed')], default='active', max_length=20)),
                ('is_controlled', models.BooleanField(default=False, help_text='Controlled substance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_created_new', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prescriptions.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_new', to='patients.patient')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prescribed_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_approvals', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='prescriptions.prescription')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionDispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('dispensed_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('dispensed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['-dispensed_date'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'status'], name='prescriptio_patient_283c70_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescribed_by', 'status'], name='prescriptio_prescri_5670ca_idx'),
        ),
    ]
