# Generated by Django 4.2.7 on 2026-03-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_temp_migration_flag',
            field=models.BooleanField(default=False, help_text='Temp field to trigger migration'),
        ),
    ]
