# Generated by Django 4.2.7 on 2026-03-24 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user__temp_migration_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_temp_migration_flag',
        ),
    ]
