# Generated by Django 4.2.7 on 2026-02-23 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_appointment'),
        ('reports', '0003_alter_report_created_by_reportattachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_prescriptions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_prescriptions', to='patients.patient'),
        ),
    ]
