# Generated by Django 4.2.7 on 2026-02-24 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_appointment_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments_app', '0002_appointment_appointmenthistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=10)),
                ('scheduled_time', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.RemoveField(
            model_name='appointmenthistory',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='appointmenthistory',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-patient_suggested_date', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_status_044efd_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_patient_7cdd87_idx',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_virtual',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='meeting_link',
        ),
        migrations.AddField(
            model_name='appointment',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('checkup', 'General Checkup'), ('followup', 'Follow-up Visit'), ('emergency', 'Emergency'), ('consultation', 'Consultation'), ('procedure', 'Procedure'), ('vaccination', 'Vaccination'), ('lab_test', 'Lab Test'), ('imaging', 'Imaging/Radiology')], default='checkup', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='estimated_duration',
            field=models.IntegerField(default=30, help_text='Estimated duration in minutes'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments_app.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_app', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for appointment'),
        ),
        migrations.AlterField(
            model_name='appointmentmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'patient_suggested_date'], name='appointment_status_801a1e_idx'),
        ),
        migrations.DeleteModel(
            name='AppointmentHistory',
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments_app.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentfeedback',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='appointments_app.appointment'),
        ),
    ]
